# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: curie
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres?sslmode=disable
    depends_on:
      - db